apiVersion: apps/v1
kind: Deployment
metadata:
  name: budjetpack-frontend
  namespace: budjetpack
  labels:
    app: budjetpack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budjetpack-frontend
  template:
    metadata:
      labels:
        app: budjetpack-frontend
    spec:
      containers:
        - name: budjetpack-frontend
          image: budjetpack-frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
