apiVersion: v1
kind: Service
metadata:
  name: budjetpack-frontend-service
  namespace: budjetpack
spec:
  type: ClusterIP # accessible uniquement DANS le cluster
  selector:
    app: budjetpack-frontend # matche les pods du Deployment
  ports:
    - port: 80 # ce qu'on appelle dans le cluster
      targetPort: 80 # ce qu'écoute le pod
